apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: namespace-template
  title: Create a Namespace
  description: Create a new namespace/project on the OpenShift cluster
  tags:
    - namespace
    - openshift
    - infrastructure
spec:
  owner: platform-team
  type: infrastructure

  parameters:
    - title: Namespace Configuration
      required:
        - namespaceName
        - owner
      properties:
        namespaceName:
          title: Namespace Name
          type: string
          description: The name of the namespace to create
          pattern: '^[a-z0-9]([-a-z0-9]*[a-z0-9])?$'
          ui:autofocus: true
        owner:
          title: Owner
          type: string
          description: The team or user that owns this namespace
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              kind: [Group, User]
        description:
          title: Description
          type: string
          description: A brief description of the namespace purpose
        environment:
          title: Environment
          type: string
          description: The environment type
          default: development
          enum:
            - development
            - staging
            - production

    - title: Resource Quotas (Optional)
      properties:
        enableResourceQuota:
          title: Enable Resource Quota
          type: boolean
          default: false
          description: Apply resource quotas to the namespace
        cpuLimit:
          title: CPU Limit
          type: string
          default: "4"
          description: Maximum CPU cores for the namespace
          ui:widget: hidden
          ui:options:
            hidden:
              condition: "{{ not parameters.enableResourceQuota }}"
        memoryLimit:
          title: Memory Limit
          type: string
          default: "8Gi"
          description: Maximum memory for the namespace

  steps:
    - id: fetch-skeleton
      name: Fetch Skeleton
      action: fetch:template
      input:
        url: ./skeleton
        values:
          namespaceName: ${{ parameters.namespaceName }}
          owner: ${{ parameters.owner }}
          description: ${{ parameters.description | default('') }}
          environment: ${{ parameters.environment }}
          enableResourceQuota: ${{ parameters.enableResourceQuota | default(false) }}
          cpuLimit: ${{ parameters.cpuLimit | default('4') }}
          memoryLimit: ${{ parameters.memoryLimit | default('8Gi') }}

    - id: apply-namespace
      name: Create Namespace
      action: kubernetes:apply
      input:
        namespaced: false
        manifest: |
          apiVersion: v1
          kind: Namespace
          metadata:
            name: ${{ parameters.namespaceName }}
            labels:
              app.kubernetes.io/managed-by: backstage
              environment: ${{ parameters.environment }}
            annotations:
              description: "${{ parameters.description | default('Created by Backstage') }}"
              owner: "${{ parameters.owner }}"

    - id: apply-resource-quota
      name: Apply Resource Quota
      if: ${{ parameters.enableResourceQuota }}
      action: kubernetes:apply
      input:
        namespaced: true
        manifest: |
          apiVersion: v1
          kind: ResourceQuota
          metadata:
            name: default-quota
            namespace: ${{ parameters.namespaceName }}
          spec:
            hard:
              limits.cpu: "${{ parameters.cpuLimit }}"
              limits.memory: "${{ parameters.memoryLimit }}"
              requests.cpu: "2"
              requests.memory: "4Gi"

  output:
    links:
      - title: View Namespace in OpenShift Console
        url: https://console-openshift-console.apps.tallgeese.ultra.lab/k8s/cluster/namespaces/${{ parameters.namespaceName }}

