---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master  # for Single Node OpenShift (SNO) and 3-node compact clusters
  name: 98-create-a-partition-for-lvmstorage
spec:
  config:
    ignition:
      version: 3.4.0
    storage:
      disks:
      - device: /dev/nvme0n1  # ADJUST THIS: update to match your server's drive (e.g., /dev/sda, /dev/nvme0n1, /dev/vda)
        partitions:
        - label: lvmstorage
          startMiB: 150000  # ADJUST THIS: let CoreOS use the first 150GB
                            # (minimum 25000 MiB, recommend 120000 MiB or more)
          sizeMiB: 0        # ADJUST THIS: any size, or "0" to use the rest of the disk
