---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 98-worker-partition-for-lvmstorage
spec:
  config:
    ignition:
      version: 3.4.0
    storage:
      disks:
      - device: /dev/nvme0n1  # Same NVMe drive as tallgeese
        partitions:
        - label: lvmstorage
          startMiB: 150000  # Let CoreOS use the first 150GB
          sizeMiB: 0        # Use the rest of the disk for LVM
