---
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
    - name: htpasswd
      type: HTPasswd
      mappingMethod: claim
      htpasswd:
        fileData:
          name: htpasswd-secret
    - name: keycloak
      type: OpenID
      mappingMethod: add
      openID:
        clientID: openshift
        clientSecret:
          name: keycloak-oidc-secret
        issuer: https://sso.ultra.lab/realms/openshift
        claims:
          preferredUsername:
            - preferred_username
          name:
            - name
          email:
            - email
          groups:
            - groups
