---
# OAuth configuration for htpasswd identity provider
# This configures OpenShift to use htpasswd file-based authentication
# The actual htpasswd data is stored in the htpasswd-secret (gitignored)
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
    - name: htpasswd
      type: HTPasswd
      mappingMethod: claim
      htpasswd:
        fileData:
          name: htpasswd-secret
