apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-oidc-secret
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-secret-store
  target:
    name: keycloak-oidc-secret
  dataFrom:
    - extract:
        key: security/keycloak-oidc
