apiVersion: v1
kind: ConfigMap
metadata:
  name: ultra-lab-ca
  namespace: openshift-config
data:
  ca-bundle.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDMDCCAhigAwIBAgIUD16/uyNDxUFEkabV+r2jJA1xSOowDQYJKoZIhvcNAQEL
    BQAwFjEUMBIGA1UEAwwLKi51bHRyYS5sYWIwHhcNMjYwNzI5MTkwMDQ1WhcNMzYw
    NzI2MTkwMDQ1WjAWMRQwEgYDVQQDDAsqLnVsdHJhLmxhYjCCASIwDQYJKoZIhvcN
    AQEBBQADggEPADCCAQoCggEBAI8hH5GtoUQWmcp6SVMc6JKgRfgfDI+QMrhUTFXs
    nzRdN7Y9NTtAv1QltWWu7guJTLsDkiFUm4VXFTOmG1yT9uudnuGiUZcZR8zHkP8j
    dEVHfw8TYxU1HvI3bqeAQwyTvSygJkGsFa3/YhsGGxVs2PCh1LRqZ1A3BJcsZW4R
    LhN1VmTDA4hzwT8T35krgIIrZmyhx3uCNxeOtOlGg9dOtdDkuw3QLe0LVl3PDK9R
    bTJhtBGBlu2aukDAKiq+BknUpebU011IZFAu5bt4K5zmN4tsYeR2mSfDX1lbY4Vi
    17dTBUJbpBjE5rsEmsZd1mRHeMY6tE8qkwvRRBgshDrv2kECAwEAAaN2MHQwHQYD
    VR0OBBYEFP4jOFgQiPLXRLCcbl8kYYT1gEVHMB8GA1UdIwQYMBaAFP4jOFgQiPLX
    RLCcbl8kYYT1gEVHMA8GA1UdEwEB/wQFMAMBAf8wIQYDVR0RBBowGIILKi51bHRy
    YS5sYWKCCXVsdHJhLmxhYjANBgkqhkiG9w0BAQsFAAOCAQEAN7liRcuGVuXFC0T+
    Am4G9zNNHLCy3WyOm+ouwEvTA3Nl5pZMNzd4OONulUX+lHXnyc5tvGgOgFAaZbTc
    2GldH+MJsVs7XFpgCYPJEtlKQ45yp0V7Jef8DSqcVb95FoDVr6vf32X+OfmlFTGu
    WnLFdHWdcUkA6a+zHSQNiXeJBTgJyPR7FTRtYdp/7SALcCOEdswwJZ8jJTRpCYnE
    FVSymSf8muYBkreO9i+WZFtSv8UsybImkG4PC1XcMFUUPCL9GVdGmo5mWZ19uIU8
    E9MwGzAEcwPWEMYOxoTLws2KRJKXIlpIqHGtMYqddHXtJTeVsPAewi5dLex1ChS4
    HqXUwA==
    -----END CERTIFICATE-----
  registry.ultra.lab: |
    -----BEGIN CERTIFICATE-----
    MIIDMDCCAhigAwIBAgIUD16/uyNDxUFEkabV+r2jJA1xSOowDQYJKoZIhvcNAQEL
    BQAwFjEUMBIGA1UEAwwLKi51bHRyYS5sYWIwHhcNMjYwNzI5MTkwMDQ1WhcNMzYw
    NzI2MTkwMDQ1WjAWMRQwEgYDVQQDDAsqLnVsdHJhLmxhYjCCASIwDQYJKoZIhvcN
    AQEBBQADggEPADCCAQoCggEBAI8hH5GtoUQWmcp6SVMc6JKgRfgfDI+QMrhUTFXs
    nzRdN7Y9NTtAv1QltWWu7guJTLsDkiFUm4VXFTOmG1yT9uudnuGiUZcZR8zHkP8j
    dEVHfw8TYxU1HvI3bqeAQwyTvSygJkGsFa3/YhsGGxVs2PCh1LRqZ1A3BJcsZW4R
    LhN1VmTDA4hzwT8T35krgIIrZmyhx3uCNxeOtOlGg9dOtdDkuw3QLe0LVl3PDK9R
    bTJhtBGBlu2aukDAKiq+BknUpebU011IZFAu5bt4K5zmN4tsYeR2mSfDX1lbY4Vi
    17dTBUJbpBjE5rsEmsZd1mRHeMY6tE8qkwvRRBgshDrv2kECAwEAAaN2MHQwHQYD
    VR0OBBYEFP4jOFgQiPLXRLCcbl8kYYT1gEVHMB8GA1UdIwQYMBaAFP4jOFgQiPLX
    RLCcbl8kYYT1gEVHMA8GA1UdEwEB/wQFMAMBAf8wIQYDVR0RBBowGIILKi51bHRy
    YS5sYWKCCXVsdHJhLmxhYjANBgkqhkiG9w0BAQsFAAOCAQEAN7liRcuGVuXFC0T+
    Am4G9zNNHLCy3WyOm+ouwEvTA3Nl5pZMNzd4OONulUX+lHXnyc5tvGgOgFAaZbTc
    2GldH+MJsVs7XFpgCYPJEtlKQ45yp0V7Jef8DSqcVb95FoDVr6vf32X+OfmlFTGu
    WnLFdHWdcUkA6a+zHSQNiXeJBTgJyPR7FTRtYdp/7SALcCOEdswwJZ8jJTRpCYnE
    FVSymSf8muYBkreO9i+WZFtSv8UsybImkG4PC1XcMFUUPCL9GVdGmo5mWZ19uIU8
    E9MwGzAEcwPWEMYOxoTLws2KRJKXIlpIqHGtMYqddHXtJTeVsPAewi5dLex1ChS4
    HqXUwA==
    -----END CERTIFICATE-----
