# Disk partitioning for LVM Storage on all master nodes
# In a compact 3-node cluster, all nodes are masters
# This manifest is baked into the Agent-based installer ISO
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 98-master-partition-for-lvmstorage
spec:
  config:
    ignition:
      version: 3.4.0
    storage:
      disks:
        - device: /dev/nvme0n1
          partitions:
            # Partition 4 is the root filesystem - limit its size
            - number: 4
              sizeMiB: 150000  # 150GB for root
              resize: true
            # Partition 5 for LVM storage
            - number: 5
              label: lvmstorage
              sizeMiB: 0  # Use all remaining space
