apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 99-master-journald-retention
spec:
  config:
    ignition:
      version: 3.4.0
    storage:
      files:
      - path: /etc/systemd/journald.conf.d/99-retention.conf
        mode: 0644
        overwrite: true
        contents:
          source: data:text/plain;charset=utf-8;base64,W0pvdXJuYWxdCiMgTGltaXQgdG90YWwgam91cm5hbCBkaXNrIHVzYWdlIHRvIDJHQgpTeXN0ZW1NYXhVc2U9MkcKIyBLZWVwIGxvZ3MgZm9yIG1heGltdW0gMzAgZGF5cwpNYXhSZXRlbnRpb25TZWM9MzBkCiMgUm90YXRlIGxvZyBmaWxlcyBkYWlseQpNYXhGaWxlU2VjPTFkCiMgS2VlcCBhdCBsZWFzdCAyNUdCIGZyZWUgb24gZGlzawpTeXN0ZW1LZWVwRnJlZT0yNUcK
---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 99-worker-journald-retention
spec:
  config:
    ignition:
      version: 3.4.0
    storage:
      files:
      - path: /etc/systemd/journald.conf.d/99-retention.conf
        mode: 0644
        overwrite: true
        contents:
          source: data:text/plain;charset=utf-8;base64,W0pvdXJuYWxdCiMgTGltaXQgdG90YWwgam91cm5hbCBkaXNrIHVzYWdlIHRvIDJHQgpTeXN0ZW1NYXhVc2U9MkcKIyBLZWVwIGxvZ3MgZm9yIG1heGltdW0gMzAgZGF5cwpNYXhSZXRlbnRpb25TZWM9MzBkCiMgUm90YXRlIGxvZyBmaWxlcyBkYWlseQpNYXhGaWxlU2VjPTFkCiMgS2VlcCBhdCBsZWFzdCAyNUdCIGZyZWUgb24gZGlzawpTeXN0ZW1LZWVwRnJlZT0yNUcK
