apiVersion: v1
kind: ConfigMap
metadata:
  name: devspaces-git-config
  namespace: openshift-devspaces
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: workspaces-config
  annotations:
    controller.devfile.io/mount-as: subpath
    controller.devfile.io/mount-path: /etc/gitconfig
data:
  gitconfig: |
    [user]
      name = Jeff Franklin
      email = jefr@redhat.com
