---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: aap-credentials
  namespace: rhdh
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-secret-store
  target:
    name: aap-credentials
  data:
    - secretKey: AAP_BASE_URL
      remoteRef:
        key: aap/admin
        property: url
    - secretKey: AAP_TOKEN
      remoteRef:
        key: aap/tokens
        property: rhdh_token
    - secretKey: AAP_OAUTH_CLIENT_ID
      remoteRef:
        key: aap/oauth
        property: client_id
    - secretKey: AAP_OAUTH_CLIENT_SECRET
      remoteRef:
        key: aap/oauth
        property: client_secret
