---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dynamic-plugins-registry-auth
  namespace: rhdh
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-secret-store
  target:
    name: dynamic-plugins-registry-auth
  dataFrom:
    - extract:
        key: rhdh/registry-auth
