---
apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: openshift-gitops
  namespace: openshift-gitops
spec:
  # Custom health checks - treat Pending PVCs (WaitForFirstConsumer) as Healthy
  resourceHealthChecks:
    - group: ""
      kind: PersistentVolumeClaim
      check: |
        hs = {}
        if obj.status ~= nil then
          if obj.status.phase ~= nil then
            if obj.status.phase == "Pending" then
              -- WaitForFirstConsumer PVCs stay Pending until consumed - that's OK
              hs.status = "Healthy"
              hs.message = "PVC is Pending (WaitForFirstConsumer)"
            elseif obj.status.phase == "Bound" then
              hs.status = "Healthy"
              hs.message = "PVC is Bound"
            else
              hs.status = "Degraded"
              hs.message = "PVC is " .. obj.status.phase
            end
          end
        end
        return hs
  sourceNamespaces:
    - a-project
  applicationSet:
    resources:
      limits:
        cpu: "2"
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 512Mi
    webhookServer:
      ingress:
        enabled: false
      route:
        enabled: false
  controller:
    processors: {}
    resources:
      limits:
        cpu: "2"
        memory: 2Gi
      requests:
        cpu: 250m
        memory: 1Gi
    sharding: {}
  grafana:
    enabled: false
    ingress:
      enabled: false
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 128Mi
    route:
      enabled: false
  ha:
    enabled: false
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 128Mi
  initialSSHKnownHosts: {}
  monitoring:
    enabled: false
  notifications:
    enabled: false
  prometheus:
    enabled: false
    ingress:
      enabled: false
    route:
      enabled: false
  rbac:
    defaultPolicy: ""
    policy: |
      # OpenShift groups -> ArgoCD admin
      g, system:cluster-admins, role:admin
      g, cluster-admins, role:admin
      # OpenShift htpasswd 'admin' user -> ArgoCD admin
      g, admin, role:admin
      # Service accounts
      g, developer-hub, role:readonly
    # Include both groups and preferred_username (for individual user matching)
    scopes: '[groups, preferred_username]'
  extraConfig:
    accounts.admin: 'apiKey, login'
    accounts.developer-hub: 'apiKey, login'
  redis:
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 128Mi
  repo:
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 256Mi
  resourceExclusions: |
    - apiGroups:
      - tekton.dev
      clusters:
      - '*'
      kinds:
      - TaskRun
      - PipelineRun
  server:
    autoscale:
      enabled: false
    grpc:
      ingress:
        enabled: false
    ingress:
      enabled: false
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 125m
        memory: 128Mi
    route:
      enabled: true
    service:
      type: ""
  sso:
    dex:
      openShiftOAuth: true
      resources:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 250m
          memory: 128Mi
    provider: dex
  tls:
    ca: {}
