apiVersion: batch/v1
kind: Job
metadata:
  name: patch-argocd-secret
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      serviceAccountName: openshift-gitops-argocd-application-controller
      containers:
      - name: patch-secret
        image: registry.redhat.io/openshift4/ose-cli:latest
        command:
        - /bin/bash
        - -c
        - |
          # This is a test password for POC purposes. Don't use it in secure applications.
          echo "Patching argocd-secret with d3v3l0p3rs password"
          oc patch secret argocd-secret -n openshift-gitops --type=merge \
            -p '{"stringData":{"accounts.developer-hub.password":"$2y$10$KnsgxceFRwN15iVJ3BxskuIJ2/qUqzaLs8.Oea1WzyvBraZxdG.eu"}}'
      restartPolicy: Never
  backoffLimit: 3
