---
apiVersion: v1
kind: Namespace
metadata:
  name: sonataflow-infra
  labels:
    name: sonataflow-infra
    openshift.io/cluster-monitoring: "true"
  annotations:
    argocd.argoproj.io/sync-wave: "0"
